#! /bin/bash

args=""
while read f; do
    outdir=build/$(dirname $f | cut -d '/' -f2-)/$(basename $f .yaml)
    args="$args $f $outdir "
done < <(find decks -name "*.yaml")

PATH=$(npm bin):$PATH fieldfare slides templates $args --watch &
live-server build -q
